Repository Telenav/osrm-backend, pull requests merged in 2019-07, with the labels that each got.

#34 Feature/improve with traffic design
  docs/design/graph/osrm-release-deployment-pipeline.mmd
  docs/design/graph/osrm-release-deployment-pipeline.mmd.png
  docs/design/graph/osrm-with-telenav-traffic-architecture.mmd
  docs/design/graph/osrm-with-telenav-traffic-architecture.mmd.png
  docs/design/graph/osrm-with-traffic-startup-flow-chart.mmd
  docs/design/graph/osrm-with-traffic-startup-flow-chart.mmd.png
  docs/design/osrm-with-telenav-traffic.md
Labels: Design

#33 Feature/k8s rolling update
  docker-orchestration/README.md
  docker-orchestration/k8s-rolling-update/README.md
  docker-orchestration/k8s-rolling-update/osrm.yaml
  docker-orchestration/k8s-rolling-update/osrm_cron
  docker-orchestration/k8s-rolling-update/osrm_svc.yaml
Labels: Implementation, Prototype

#32 Feature/integrate wayid2nodeid extractor
  docker-orchestration/osrm-backend/Dockerfile
  docker-orchestration/osrm-backend/docker-entrypoint.sh
Labels: Implementation

#37 Feature/export pod logs
  docker-orchestration/k8s-rolling-update/osrm.yaml
  docker-orchestration/osrm-backend/Dockerfile
Labels: enhancement

#41 Feature/optimize traffic convertor
  traffic_updater/go/osrm_traffic_updater/get_telenav_traffic.go
  traffic_updater/go/osrm_traffic_updater/osrm_speedtable_generator.go
  traffic_updater/go/osrm_traffic_updater/osrm_speedtable_generator_test.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater_test.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper_test.go
  traffic_updater/go/osrm_traffic_updater/testdata/expect.csv
  traffic_updater/go/osrm_traffic_updater/testdata/id-mapping-delta.csv
  traffic_updater/go/osrm_traffic_updater/testdata/id-mapping-delta.csv.snappy
  traffic_updater/go/osrm_traffic_updater/testdata/id-mapping.csv
  traffic_updater/go/osrm_traffic_updater/testdata/id-mapping.csv.snappy
  traffic_updater/go/osrm_traffic_updater/testdata/mock-traffic.csv
  traffic_updater/go/osrm_traffic_updater/testdata/target.csv
  traffic_updater/go/osrm_traffic_updater/way2nodeids_loader.go
  traffic_updater/go/osrm_traffic_updater/way2nodeids_loader_test.go
  traffic_updater/go/snappy_command/snappy_command.go
  traffic_updater/go/wayid2nodeid_extractor/wayid2nodeids_extractor.go
Labels: enhancement

#44 Feature/traffic updater statistic
  traffic_updater/go/osrm_traffic_updater/dumper_statistic.go
  traffic_updater/go/osrm_traffic_updater/dumper_statistic_test.go
  traffic_updater/go/osrm_traffic_updater/get_telenav_traffic.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater_test.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper_test.go
Labels: enhancement

#46 Add traffic records matched statistics and total processing time
  traffic_updater/go/osrm_traffic_updater/dumper_statistic.go
  traffic_updater/go/osrm_traffic_updater/dumper_statistic_test.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper.go
Labels: enhancement

#47 chore: format our golang codes by 'goreturns -l -w .'
  traffic_updater/go/osrm_traffic_updater/get_telenav_traffic.go
  traffic_updater/go/osrm_traffic_updater/osrm_traffic_updater_test.go
  traffic_updater/go/osrm_traffic_updater/speed_table_dumper_test.go
  traffic_updater/go/osrm_traffic_updater/way2nodeids_loader.go
  traffic_updater/go/osrm_traffic_updater/way2nodeids_loader_test.go
  traffic_updater/go/snappy_command/snappy_command.go
  traffic_updater/go/wayid2nodeid_extractor/wayid2nodeids_extractor.go
Labels: enhancement
