Repository Telenav/osrm-backend, pull requests merged in 2020-04, with the labels that each got.

#258 Feature/Implement ranker for handling near by points/places
  integration/go.mod
  integration/go.sum
  integration/service/spatialindexer/doc.go
  integration/service/spatialindexer/interface.go
  integration/service/spatialindexer/ranker/doc.go
  integration/service/spatialindexer/ranker/osrm_ranker.go
  integration/service/spatialindexer/ranker/osrm_ranker_test.go
  integration/service/spatialindexer/ranker/rank_agent.go
  integration/service/spatialindexer/ranker/rank_agent_test.go
  integration/service/spatialindexer/ranker/rank_by_great_circle_distance_impl.go
  integration/service/spatialindexer/ranker/rank_by_osrm_shortest_path_impl.go
  integration/service/spatialindexer/ranker/rank_by_osrm_shortest_path_impl_test.go
  integration/service/spatialindexer/ranker/ranker_factory.go
  integration/service/spatialindexer/ranker/simple_ranker.go
  integration/service/spatialindexer/ranker/simple_ranker_test.go
  integration/service/spatialindexer/s2indexer/builder.go
  integration/service/spatialindexer/s2indexer/builder_test.go
  integration/service/spatialindexer/s2indexer/dumper_test.go
  integration/service/spatialindexer/s2indexer/indexer.go
  integration/service/spatialindexer/s2indexer/spatial_query.go
  integration/service/spatialindexer/s2indexer/spatial_query_test.go
Labels: InProgress, Prototype

#261 Refactor: move ranking service into service folder
  integration/cmd/osrm-ranking/main.go
  integration/service/ranking/flags.go
  integration/service/ranking/handler.go
  integration/service/ranking/post_process.go
  integration/service/ranking/route_by_osrm.go
  integration/service/ranking/strategy/rankbyduration/rank.go
  integration/service/ranking/strategy/rankbyduration/rank_test.go
  integration/service/ranking/update_by_traffic.go
Labels: Refactor

#259 Feature/Implement connectivity map
  integration/service/connectivitymap/builder.go
  integration/service/connectivitymap/builder_test.go
  integration/service/connectivitymap/connectivity_map.go
  integration/service/connectivitymap/connectivity_map_mock.go
  integration/service/connectivitymap/doc.go
  integration/service/connectivitymap/dumper.go
  integration/service/connectivitymap/dumper_test.go
  integration/service/connectivitymap/statistic.go
  integration/service/connectivitymap/statistic_test.go
  integration/service/spatialindexer/interface.go
  integration/service/spatialindexer/interface_mock.go
  integration/service/spatialindexer/ranker/ranker_factory.go
  integration/service/spatialindexer/s2indexer/indexer.go
  integration/service/spatialindexer/s2indexer/spatial_query.go
  integration/service/spatialindexer/s2indexer/spatial_query_test.go
Labels: InProgress, NewFeature, Prototype

#268 Feature/Implement the tool to generate connectivity map for places
  integration/cmd/place-connectivity-gen/doc.go
  integration/cmd/place-connectivity-gen/flags.go
  integration/cmd/place-connectivity-gen/main.go
  integration/cmd/poi-converter/main.go
  integration/oasis/osrmconnector/osrmhttpclient.go
  integration/oasis/reachable_by_single_charge.go
  integration/oasis/stationfinder/stations_iterator_alg.go
  integration/pkg/api/osrm/table/mock_response.go
  integration/pkg/api/osrm/table/response.go
  integration/service/connectivitymap/builder.go
  integration/service/connectivitymap/connectivity_map.go
  integration/service/connectivitymap/dumper.go
  integration/service/connectivitymap/statistic.go
  integration/service/connectivitymap/statistic_test.go
  integration/service/spatialindexer/poiloader/loader.go
  integration/service/spatialindexer/poiloader/poi_format.go
  integration/service/spatialindexer/ranker/osrm_ranker_test.go
  integration/service/spatialindexer/ranker/rank_by_great_circle_distance_impl.go
  integration/service/spatialindexer/ranker/rank_by_osrm_shortest_path_impl.go
  integration/service/spatialindexer/ranker/rank_by_osrm_shortest_path_impl_test.go
  integration/service/spatialindexer/s2indexer/builder.go
  integration/service/spatialindexer/s2indexer/builder_test.go
  integration/service/spatialindexer/s2indexer/indexer.go
  integration/service/spatialindexer/s2indexer/spatial_query.go
Labels: Bug, NewFeature, Prototype

#271 refactor: Refactor station finder to support multiple strategy
  integration/cmd/oasis/flags.go
  integration/cmd/oasis/main.go
  integration/service/oasis/handler.go
  integration/service/oasis/reachable_by_multiple_charge.go
  integration/service/oasis/reachable_by_single_charge.go
  integration/service/oasis/stationfinder/dest_iterator.go
  integration/service/oasis/stationfinder/dest_station_finder_test.go
  integration/service/oasis/stationfinder/doc.go
  integration/service/oasis/stationfinder/interface.go
  integration/service/oasis/stationfinder/low_energy_location_station_finder_test.go
  integration/service/oasis/stationfinder/orig_iterator.go
  integration/service/oasis/stationfinder/station_finder_factory.go
  integration/service/oasis/stationfinder/stationfinderalg/dest_iterator.go
  integration/service/oasis/stationfinder/stationfinderalg/orig_iterator.go
  integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg.go
  integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg_test.go
  integration/service/oasis/stationfinder/stationfindertype/const.go
  integration/service/oasis/stationfinder/stationfindertype/type.go
  integration/service/oasis/stationfinder/stations_iterator.go
  integration/service/oasis/stationfinder/tnsearchfinder/basic_finder.go
  integration/service/oasis/stationfinder/tnsearchfinder/basic_finder_test.go
  integration/service/oasis/stationfinder/tnsearchfinder/dest_station_finder.go
  integration/service/oasis/stationfinder/tnsearchfinder/dest_station_finder_mock.go
  integration/service/oasis/stationfinder/tnsearchfinder/dest_station_finder_test.go
  integration/service/oasis/stationfinder/tnsearchfinder/low_energy_location_station_finder.go
  integration/service/oasis/stationfinder/tnsearchfinder/low_energy_location_station_finder_mock.go
  integration/service/oasis/stationfinder/tnsearchfinder/low_energy_location_station_finder_test.go
  integration/service/oasis/stationfinder/tnsearchfinder/orig_station_finder.go
  integration/service/oasis/stationfinder/tnsearchfinder/orig_station_finder_mock.go
  integration/service/oasis/stationfinder/tnsearchfinder/orig_station_finder_test.go
  integration/service/oasis/stationfinder/tnsearchfinder/tnsearch_station_finder.go
  integration/service/oasis/stationgraph/station_graph.go
  integration/service/oasis/stationgraph/station_graph_test.go
Labels: Refactor

#277 Refactor: pkg/wayidsflag -> util/idsflag
  integration/cmd/nodes2way-cli/flags.go
  integration/cmd/trafficproxy-cli/flags.go
  integration/pkg/wayidsflag/wayids_flag.go
  integration/pkg/wayidsflag/wayids_flag_test.go
  integration/util/idsflag/ids_flag.go
  integration/util/idsflag/ids_flag_test.go
Labels: Refactor

#280 refactor: use `struct embedding` to avoid interface forwarding
  integration/cmd/oasis/flags.go
  integration/service/oasis/stationfinder/cloudfinder/cloud_station_finder.go
  integration/service/oasis/stationfinder/cloudfinder/dest_station_finder.go
  integration/service/oasis/stationfinder/cloudfinder/dest_station_finder_mock.go
  integration/service/oasis/stationfinder/cloudfinder/dest_station_finder_test.go
  integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder.go
  integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder_mock.go
  integration/service/oasis/stationfinder/cloudfinder/low_energy_location_station_finder_test.go
  integration/service/oasis/stationfinder/cloudfinder/orig_station_finder.go
  integration/service/oasis/stationfinder/cloudfinder/orig_station_finder_mock.go
  integration/service/oasis/stationfinder/cloudfinder/orig_station_finder_test.go
  integration/service/oasis/stationfinder/localfinder/dest_station_local_finder.go
  integration/service/oasis/stationfinder/localfinder/low_energy_location_local_finder.go
  integration/service/oasis/stationfinder/localfinder/orig_station_local_finder.go
  integration/service/oasis/stationfinder/station_finder_factory.go
  integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg_test.go
Labels: Refactor

#283 Add CHANGELOG-FORK.md and improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG-FORK.md
Labels: Chore

#285 Fix invalid nodes in annotations of response
  CHANGELOG-FORK.md
  docs/http.md
  include/engine/api/route_api.hpp
Labels: Bug

#286 Build nodes2way DB when compile mapdata
  CHANGELOG-FORK.md
  docker-orchestration/osrm-backend-within-mapdata/Dockerfile
  docker-orchestration/osrm-backend/docker-entrypoint.sh
Labels: Chore

#300 Refactor: Move unidbpatch and mapsource Packages into util Folder
  CHANGELOG-FORK.md
  integration/cmd/historicalspeed-timezone-builder/flags.go
  integration/cmd/historicalspeed-timezone-builder/main.go
  integration/cmd/historicalspeed-timezone-builder/timezone_builder.go
  integration/cmd/wayid2nodeid-extractor/flags.go
  integration/cmd/wayid2nodeid-extractor/wayid2nodeids_extractor.go
  integration/util/mapsource/definition.go
  integration/util/unidbpatch/patch.go
  integration/util/unidbpatch/patch_test.go
Labels: Refactor

#305 Add `merge=union` for resolving merge confilcits automatically on CHANGELOG-FORK.md
  .gitattributes
  CHANGELOG-FORK.md
Labels: Chore

#303 Use way indexed live traffic cache in osrm-ranking
  CHANGELOG-FORK.md
  integration/cmd/osrm-ranking/flags.go
  integration/cmd/osrm-ranking/main.go
  integration/cmd/osrm-ranking/monitor.go
  integration/service/ranking/handler.go
  integration/service/ranking/update_by_traffic.go
Labels: NewFeature, Prototype

#307 refactor: change `edgeIDAndData` to `edge` and replace location defin…
  CHANGELOG-FORK.md
  integration/service/oasis/stationfinder/stationfinderalg/stations_iterator_alg.go
  integration/service/oasis/stationgraph/edge.go
  integration/service/oasis/stationgraph/graph_interface.go
  integration/service/oasis/stationgraph/graph_mock.go
  integration/service/oasis/stationgraph/node.go
  integration/service/oasis/stationgraph/node_container.go
  integration/service/oasis/stationgraph/node_container_test.go
  integration/service/oasis/stationgraph/node_graph.go
  integration/service/oasis/stationgraph/node_graph_test.go
  integration/service/oasis/stationgraph/station_graph.go
  integration/service/oasis/stationgraph/station_graph_test.go
Labels: Refactor

#313 Auto compile sample data
  .github/workflows/autobuild-osrm-backend.yml
  CHANGELOG-FORK.md
Labels: Chore
