Repository Telenav/osrm-backend, pull requests merged in 2020-03, with the labels that each got.

#184 Feature/implement logic for finding charge stations when energy is low
  integration/oasis/stationfinder/basic_finder.go
  integration/oasis/stationfinder/basic_finder_test.go
  integration/oasis/stationfinder/dest_station_finder.go
  integration/oasis/stationfinder/dest_station_finder_test.go
  integration/oasis/stationfinder/low_energy_location_station_finder.go
  integration/oasis/stationfinder/low_energy_location_station_finder_test.go
  integration/oasis/stationfinder/orig_station_finder.go
  integration/oasis/stationfinder/orig_station_finder_test.go
Labels: Prototype

#190 Build/Release osrm-backend-dev and osrm-backend docker automation by GitHub Actions
  .github/workflows/autobuild-osrm-backend-dev.yml
  .github/workflows/autobuild-osrm-backend.yml
  .github/workflows/release-osrm-backend-dev.yml
  .github/workflows/release-osrm-backend.yml
  README.md
  docker-orchestration/README.md
  docker-orchestration/osrm-backend-dev/Dockerfile
  docker-orchestration/osrm-backend/Dockerfile
  docker-orchestration/osrm-backend/README.md
Labels: Chore

#189 Feature/Generate connectivity between charge stations near to low energy point
  integration/oasis/reachable_by_multiple_charge.go
  integration/oasis/reachable_by_single_charge.go
  integration/oasis/stationfinder/basic_finder_test.go
  integration/oasis/stationfinder/dest_iterator.go
  integration/oasis/stationfinder/dest_station_finder_test.go
  integration/oasis/stationfinder/doc.go
  integration/oasis/stationfinder/low_energy_location_station_finder_test.go
  integration/oasis/stationfinder/orig_iterator.go
  integration/oasis/stationfinder/orig_station_finder_test.go
  integration/oasis/stationfinder/stations_iterator_alg.go
  integration/oasis/stationfinder/stations_iterator_alg_test.go
  integration/oasis/stationgraph/station_graph.go
  integration/pkg/api/osrm/table/mock_response.go
  integration/pkg/api/search/nearbychargestation/mock_response.go
  integration/pkg/api/search/nearbychargestation/request.go
  integration/pkg/api/search/nearbychargestation/request_test.go
Labels: Prototype

#194 Implement station graph
  integration/oasis/chargingstrategy/charge_strategy_creator.go
  integration/oasis/chargingstrategy/chargingstrategy.go
  integration/oasis/chargingstrategy/doc.go
  integration/oasis/reachable_by_multiple_charge.go
  integration/oasis/stationfinder/dest_iterator.go
  integration/oasis/stationfinder/orig_iterator.go
  integration/oasis/stationfinder/stations_iterator_alg.go
  integration/oasis/stationfinder/stations_iterator_alg_test.go
  integration/oasis/stationgraph/station_graph.go
  integration/oasis/stationgraph/station_graph_test.go
Labels: Prototype

#210 Golang CI
  .github/workflows/go-ci.yml
  .github/workflows/release-go-cmd-osrm-files-extractor.yml
  .github/workflows/release-go-cmd-traffixproxy-cli.yml
Labels: Chore

#205 feat: implement type to record internal solution
  integration/oasis/solution/doc.go
  integration/oasis/solution/solution.go
Labels: Prototype

#206 fix: Record location inforamtion on neighbors
  integration/oasis/stationfinder/stations_iterator_alg.go
  integration/oasis/stationfinder/stations_iterator_alg_test.go
Labels: Prototype

#207 fix: fix issue in graph for handling charge state
  integration/oasis/stationgraph/graph.go
  integration/oasis/stationgraph/graph_test.go
  integration/oasis/stationgraph/node.go
  integration/oasis/stationgraph/query_heap.go
Labels: Prototype

#213 Use osrm-backend-dev/v1 as base image for stable purpose
  docker-orchestration/osrm-backend/Dockerfile
Labels: Chore

#204 feat: Implement function to calcualte charge cost
  integration/oasis/chargingstrategy/charge_strategy_creator.go
  integration/oasis/chargingstrategy/chargingstrategy.go
  integration/oasis/chargingstrategy/chargingstrategy_test.go
  integration/oasis/chargingstrategy/null_charge_strategy.go
  integration/oasis/stationgraph/station_graph.go
  integration/oasis/stationgraph/station_graph_test.go
  integration/util/float_operation.go
  integration/util/float_operation_test.go
Labels: Prototype

#215 Feature/Implement function of GenerateChargeSolutions for station_graph
  integration/oasis/handler.go
  integration/oasis/reachable_by_multiple_charge.go
  integration/oasis/reachable_by_single_charge.go
  integration/oasis/stationgraph/graph.go
  integration/oasis/stationgraph/graph_test.go
  integration/oasis/stationgraph/node.go
  integration/oasis/stationgraph/station_graph.go
  integration/oasis/stationgraph/station_graph_test.go
Labels: Prototype

#225 feat: Add api document
  integration/doc/oasis/api.md
Labels: Design, Prototype

#224 fix: refactor code for oasis service, more details please go to #223
  integration/oasis/chargingstrategy/charge_strategy_creator.go
  integration/oasis/chargingstrategy/fake_charge_strategy.go
  integration/oasis/chargingstrategy/fake_charge_strategy_test.go
  integration/oasis/chargingstrategy/null_charge_strategy.go
  integration/oasis/chargingstrategy/strategy_interface.go
  integration/oasis/has_enough_energy_test.go
  integration/oasis/haversine/distance_test.go
  integration/oasis/reachable_by_multiple_charge.go
  integration/oasis/stationfinder/stations_iterator_alg_test.go
  integration/oasis/stationgraph/graph.go
  integration/oasis/stationgraph/graph_test.go
  integration/oasis/stationgraph/node.go
  integration/oasis/stationgraph/station_graph.go
  integration/oasis/stationgraph/station_graph_test.go
  integration/pkg/api/oasis/request.go
Labels: Prototype

#233 Compatible to compile mapdata from osm or unidb
  docker-orchestration/osrm-backend/README.md
  docker-orchestration/osrm-backend/docker-entrypoint.sh
  docker-orchestration/osrm-backend/example-berlin-osm.md
Labels: Chore

#229 feat: add release action for oasis service
  .github/workflows/release-go-cmd-oasis.yml
Labels: Prototype

#230 feat: integrate logic for handling multiple charge stations
  integration/oasis/handler.go
  integration/oasis/has_enough_energy.go
  integration/oasis/osrmhelper/helper.go
  integration/oasis/reachable_by_multiple_charge.go
  integration/oasis/solution/solution.go
  integration/pkg/api/oasis/mock_response.go
Labels: Prototype

#246 Helm Charts for Generic Kubernetes Deployment
  docker-orchestration/helm-chart/osrm-backend/Chart.yaml
  docker-orchestration/helm-chart/osrm-backend/na-values.yml
  docker-orchestration/helm-chart/osrm-backend/templates/deployment.yaml
  docker-orchestration/helm-chart/osrm-backend/templates/service.yaml
  docker-orchestration/helm-chart/osrm-backend/values.yaml
  docker-orchestration/helm-chart/osrm-frontend/Chart.yaml
  docker-orchestration/helm-chart/osrm-frontend/templates/deployment.yaml
  docker-orchestration/helm-chart/osrm-frontend/templates/service.yaml
  docker-orchestration/helm-chart/osrm-frontend/values.yaml
Labels: Chore

#249 osrm-backend CI: master/release branch build check and PR build check
  .github/workflows/osrm-backend-ci.yml
  README.md
Labels: Chore

#248 Feature/Build spatial index based on google::s2
  integration/cmd/chargestations-connectivity-gen/doc.go
  integration/cmd/chargestations-connectivity-gen/main.go
  integration/go.mod
  integration/go.sum
  integration/service/spatialindexer/doc.go
  integration/service/spatialindexer/interface.go
  integration/service/spatialindexer/poiloader/loader.go
  integration/service/spatialindexer/poiloader/poi_format.go
  integration/service/spatialindexer/poiloader/sample_input.json
  integration/service/spatialindexer/s2indexer/builder.go
  integration/service/spatialindexer/s2indexer/builder_test.go
  integration/service/spatialindexer/s2indexer/dumper.go
  integration/service/spatialindexer/s2indexer/dumper_test.go
  integration/service/spatialindexer/s2indexer/indexer.go
  integration/service/spatialindexer/s2indexer/spatial_query.go
  integration/service/spatialindexer/s2indexer/spatial_query_test.go
Labels: Prototype

#247 feat: implement tools to convert from csv to json
  integration/cmd/poi-converter/flags.go
  integration/cmd/poi-converter/main.go
Labels: Prototype
