Repository Telenav/osrm-backend, pull requests merged in 2020-01, with the labels that each got.

#119 support all route options
  integration/pkg/api/const.go
  integration/pkg/api/osrm/coordinate/index.go
  integration/pkg/api/osrm/coordinate/index_test.go
  integration/pkg/api/osrm/genericoptions/elements.go
  integration/pkg/api/osrm/genericoptions/elements_test.go
  integration/pkg/api/osrm/genericoptions/exclude.go
  integration/pkg/api/osrm/genericoptions/exclude_test.go
  integration/pkg/api/osrm/genericoptions/generic_hints.go
  integration/pkg/api/osrm/genericoptions/generic_hints_test.go
  integration/pkg/api/osrm/genericoptions/values.go
  integration/pkg/api/osrm/route/options/options_test.go
  integration/pkg/api/osrm/route/options/parse.go
  integration/pkg/api/osrm/route/options/values.go
  integration/pkg/api/osrm/route/request.go
  integration/pkg/api/osrm/route/request_test.go
  integration/pkg/api/url_parse_query.go
  integration/pkg/api/url_parse_query_test.go
Labels: Implementation, enhancement

#130 Feature/oasis api
  integration/cmd/oasis/flags.go
  integration/cmd/oasis/main.go
  integration/oasis/handler.go
  integration/pkg/api/oasis/options/key.go
  integration/pkg/api/oasis/options/values.go
  integration/pkg/api/oasis/request.go
  integration/pkg/api/oasis/request_test.go
  integration/pkg/api/oasis/response.go
Labels: Implementation, Prototype

#135 Implement initial connector with Telenav search
  integration/cmd/search-adhoc-request/flags.go
  integration/cmd/search-adhoc-request/main.go
  integration/pkg/api/search/coordinate/coordinate.go
  integration/pkg/api/search/nearbychargestation/request.go
  integration/pkg/api/search/nearbychargestation/response.go
  integration/pkg/api/search/options/key.go
  integration/pkg/api/search/options/value.go
Labels: Prototype

#138 Feature/observe dot timestamp
  integration/README.md
  integration/cmd/osrm-files-extractor/flags.go
  integration/cmd/osrm-files-extractor/main.go
  integration/osrmfiles/contents_interface.go
  integration/osrmfiles/dotosrm/contents.go
  integration/osrmfiles/dotosrmdottimestamp/contents.go
  integration/osrmfiles/tar_loader.go
Labels: Prototype, Research
